BEGIN IMMEDIATE;
CREATE TABLE metadata (id INTEGER PRIMARY KEY CHECK(id=1), revision INTEGER NOT NULL DEFAULT 0);
INSERT INTO metadata(id,revision) VALUES(1,0);
CREATE TABLE subjects (id TEXT PRIMARY KEY, name TEXT NOT NULL CHECK(length(name)>0), color TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE countries (id TEXT PRIMARY KEY, name TEXT NOT NULL CHECK(length(name)>0), color TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE topics (id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES subjects(id) DEFERRABLE INITIALLY DEFERRED, parent_id TEXT REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, mastery INTEGER NOT NULL CHECK(mastery BETWEEN 0 AND 3), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX topics_subject ON topics(subject_id);
CREATE INDEX topics_mastery ON topics(mastery);
CREATE TABLE nodes (id TEXT PRIMARY KEY, topic_id TEXT NOT NULL UNIQUE REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, country_id TEXT REFERENCES countries(id) DEFERRABLE INITIALLY DEFERRED, x INTEGER NOT NULL, y INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX nodes_country ON nodes(country_id);
CREATE TABLE relations (id TEXT PRIMARY KEY, from_id TEXT NOT NULL REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, to_id TEXT NOT NULL REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE sessions (id TEXT PRIMARY KEY, topic_id TEXT NOT NULL REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, subtopic_id TEXT REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, started_at INTEGER NOT NULL, duration_ms INTEGER NOT NULL CHECK(duration_ms>=0), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX sessions_date ON sessions(started_at);
CREATE INDEX sessions_topic ON sessions(topic_id);
CREATE TABLE tests (id TEXT PRIMARY KEY, topic_id TEXT NOT NULL REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, date INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX tests_topic ON tests(topic_id);
CREATE TABLE settings (id TEXT PRIMARY KEY CHECK(id='preferences'), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE timer (id TEXT PRIMARY KEY CHECK(id='active'), topic_id TEXT NOT NULL REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, subtopic_id TEXT REFERENCES topics(id) DEFERRABLE INITIALLY DEFERRED, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE civilization (id TEXT PRIMARY KEY CHECK(id='civilization'), data TEXT NOT NULL CHECK(json_valid(data)));
PRAGMA user_version=2;
COMMIT;
